import type { DiffDocument } from "./diff.js";

export interface ExplainOperation {
  id: string;
  type: DiffDocument["operations"][number]["type"];
  rationale: string;
  confidence?: number;
  moveId?: string;
  renameGroupId?: string;
}

export interface ExplainDocument {
  version: "0.1.0";
  operations: ExplainOperation[];
  moves: {
    id: string;
    confidence: number;
    rationale: string;
  }[];
  renames: {
    id: string;
    from: string;
    to: string;
    occurrences: number;
    confidence: number;
    rationale: string;
  }[];
}

export function explainDiff(diff: DiffDocument): ExplainDocument {
  return {
    version: "0.1.0",
    operations: diff.operations.map((op) => {
      const entry: ExplainOperation = {
        id: op.id,
        type: op.type,
        rationale: `Operation ${op.type} generated by structural diff.`,
      };
      if (op.meta?.confidence !== undefined) {
        entry.confidence = op.meta.confidence;
      }
      if (op.meta?.moveId !== undefined) {
        entry.moveId = op.meta.moveId;
      }
      if (op.meta?.renameGroupId !== undefined) {
        entry.renameGroupId = op.meta.renameGroupId;
      }
      return entry;
    }),
    moves: diff.moves.map((move) => ({
      id: move.id,
      confidence: move.confidence,
      rationale: `Move detected for ${move.operations.length} operations.`,
    })),
    renames: diff.renames.map((rename) => ({
      id: rename.id,
      from: rename.from,
      to: rename.to,
      occurrences: rename.occurrences,
      confidence: rename.confidence,
      rationale: `Rename pattern detected ${rename.occurrences} times.`,
    })),
  };
}
