import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type {
  DiagnosticsBundle,
  DiffDocument,
  DiffOperation,
  ExplainDocument,
  Range,
} from "@semadiff/core";
import type { LanguageId, TokenRange } from "@semadiff/parsers";
import { renderHtml } from "@semadiff/render-html";

const DEFAULT_CONTEXT_LINES = 3;
const EXTERNAL_FONT_IMPORT_RE = /@import url\([^\n]+\);\n\n/;

export interface InspectWorkbenchInput {
  oldPath: string;
  newPath: string;
  oldText: string;
  newText: string;
  language?: LanguageId;
  diff: DiffDocument;
  explain: ExplainDocument;
  diagnostics: DiagnosticsBundle;
  oldTokens?: readonly TokenRange[];
  newTokens?: readonly TokenRange[];
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function escapeScript(value: string) {
  return value
    .replace(/<\/script/gi, "<\\/script")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function stripExternalFontImport(html: string) {
  return html.replace(EXTERNAL_FONT_IMPORT_RE, "");
}

function displayPath(filePath: string) {
  return filePath === "-" ? "<stdin>" : filePath;
}

function formatRange(range?: Range) {
  if (!range) {
    return "—";
  }
  if (range.start.line === range.end.line) {
    if (range.start.column === range.end.column) {
      return `L${range.start.line}:${range.start.column}`;
    }
    return `L${range.start.line}:${range.start.column}-${range.end.column}`;
  }
  return `L${range.start.line}:${range.start.column}-L${range.end.line}:${range.end.column}`;
}

function formatConfidence(confidence?: number) {
  return confidence === undefined ? "n/a" : `${Math.round(confidence * 100)}%`;
}

function countOperationsByType(diff: DiffDocument) {
  const counts: Record<DiffOperation["type"], number> = {
    insert: 0,
    delete: 0,
    update: 0,
    move: 0,
  };
  for (const operation of diff.operations) {
    counts[operation.type] += 1;
  }
  return counts;
}

function buildSemanticTokensOption(
  oldTokens?: readonly TokenRange[],
  newTokens?: readonly TokenRange[]
) {
  if (!(oldTokens || newTokens)) {
    return {};
  }
  return {
    semanticTokens: {
      ...(oldTokens ? { old: oldTokens } : {}),
      ...(newTokens ? { new: newTokens } : {}),
    },
  };
}

function renderVariantHtml(
  diff: DiffDocument,
  options: Parameters<typeof renderHtml>[1]
) {
  return stripExternalFontImport(renderHtml(diff, options));
}

function buildOperationItems(diff: DiffDocument, explain: ExplainDocument) {
  if (diff.operations.length === 0) {
    return '<div class="sdx-empty">No semantic operations were generated for this file pair.</div>';
  }

  const explainById = new Map(
    explain.operations.map((operation) => [operation.id, operation])
  );
  return diff.operations
    .map((operation) => {
      const explained = explainById.get(operation.id);
      const confidence = explained?.confidence ?? operation.meta?.confidence;
      const pills = [
        `<span class="sdx-pill">Confidence ${escapeHtml(formatConfidence(confidence))}</span>`,
        ...(explained?.moveId
          ? [
              `<span class="sdx-pill">Move ${escapeHtml(explained.moveId)}</span>`,
            ]
          : []),
        ...(explained?.renameGroupId
          ? [
              `<span class="sdx-pill">Rename ${escapeHtml(explained.renameGroupId)}</span>`,
            ]
          : []),
      ].join("");

      return `<article class="sdx-item">
  <div class="sdx-item-header">
    <div class="sdx-item-title">
      <span class="sdx-type sdx-type--${escapeHtml(operation.type)}">${escapeHtml(operation.type)}</span>
      <code>${escapeHtml(operation.id)}</code>
    </div>
    <span class="sdx-item-confidence">${escapeHtml(formatConfidence(confidence))}</span>
  </div>
  <div class="sdx-range-grid">
    <div><span class="sdx-range-label">Old</span><code>${escapeHtml(formatRange(operation.oldRange))}</code></div>
    <div><span class="sdx-range-label">New</span><code>${escapeHtml(formatRange(operation.newRange))}</code></div>
  </div>
  <p class="sdx-item-copy">${escapeHtml(
    explained?.rationale ?? "Operation generated by structural diff."
  )}</p>
  <div class="sdx-pill-row">${pills}</div>
</article>`;
    })
    .join("");
}

function buildMoveItems(diff: DiffDocument, explain: ExplainDocument) {
  if (diff.moves.length === 0) {
    return '<div class="sdx-empty">No move groups detected.</div>';
  }

  const explainById = new Map(explain.moves.map((move) => [move.id, move]));
  return diff.moves
    .map((move) => {
      const explained = explainById.get(move.id);
      return `<article class="sdx-item">
  <div class="sdx-item-header">
    <div class="sdx-item-title">
      <span class="sdx-type sdx-type--move">move</span>
      <code>${escapeHtml(move.id)}</code>
    </div>
    <span class="sdx-item-confidence">${escapeHtml(
      formatConfidence(move.confidence)
    )}</span>
  </div>
  <div class="sdx-range-grid">
    <div><span class="sdx-range-label">Old</span><code>${escapeHtml(formatRange(move.oldRange))}</code></div>
    <div><span class="sdx-range-label">New</span><code>${escapeHtml(formatRange(move.newRange))}</code></div>
  </div>
  <p class="sdx-item-copy">${escapeHtml(
    explained?.rationale ??
      `Move group contains ${move.operations.length} operations.`
  )}</p>
  <div class="sdx-pill-row">
    <span class="sdx-pill">${move.operations.length} linked operations</span>
  </div>
</article>`;
    })
    .join("");
}

function buildRenameItems(diff: DiffDocument, explain: ExplainDocument) {
  if (diff.renames.length === 0) {
    return '<div class="sdx-empty">No rename groups detected.</div>';
  }

  const explainById = new Map(
    explain.renames.map((rename) => [rename.id, rename])
  );
  return diff.renames
    .map((rename) => {
      const explained = explainById.get(rename.id);
      return `<article class="sdx-item">
  <div class="sdx-item-header">
    <div class="sdx-item-title">
      <span class="sdx-type sdx-type--update">rename</span>
      <code>${escapeHtml(rename.id)}</code>
    </div>
    <span class="sdx-item-confidence">${escapeHtml(
      formatConfidence(rename.confidence)
    )}</span>
  </div>
  <p class="sdx-item-copy"><code>${escapeHtml(rename.from)}</code> → <code>${escapeHtml(rename.to)}</code></p>
  <p class="sdx-item-copy">${escapeHtml(
    explained?.rationale ??
      `Rename pattern detected ${rename.occurrences} times.`
  )}</p>
  <div class="sdx-pill-row">
    <span class="sdx-pill">${rename.occurrences} occurrences</span>
  </div>
</article>`;
    })
    .join("");
}

export function renderInspectWorkbench(input: InspectWorkbenchInput) {
  const shownOldPath = displayPath(input.oldPath);
  const shownNewPath = displayPath(input.newPath);
  const preferredPath =
    shownNewPath !== "<stdin>" ? shownNewPath : shownOldPath;
  const title = `SemaDiff Inspect · ${path.basename(shownOldPath)} ↔ ${path.basename(shownNewPath)}`;
  const semanticTokensOption = buildSemanticTokensOption(
    input.oldTokens,
    input.newTokens
  );
  const languageOption = input.language ? { language: input.language } : {};
  const operationCounts = countOperationsByType(input.diff);

  const views = {
    semanticStructure: renderVariantHtml(input.diff, {
      title,
      filePath: preferredPath,
      view: "semantic",
      oldText: input.oldText,
      newText: input.newText,
      showBanner: false,
      showSummary: false,
      showFilePath: false,
      layout: "embed",
      ...languageOption,
      ...semanticTokensOption,
    }),
    semanticUnified: renderVariantHtml(input.diff, {
      title,
      filePath: preferredPath,
      view: "lines",
      lineMode: "semantic",
      oldText: input.oldText,
      newText: input.newText,
      contextLines: DEFAULT_CONTEXT_LINES,
      lineLayout: "unified",
      showBanner: false,
      showSummary: false,
      showFilePath: false,
      layout: "embed",
      ...languageOption,
      ...semanticTokensOption,
    }),
    semanticSplit: renderVariantHtml(input.diff, {
      title,
      filePath: preferredPath,
      view: "lines",
      lineMode: "semantic",
      oldText: input.oldText,
      newText: input.newText,
      contextLines: DEFAULT_CONTEXT_LINES,
      lineLayout: "split",
      showBanner: false,
      showSummary: false,
      showFilePath: false,
      layout: "embed",
      ...languageOption,
      ...semanticTokensOption,
    }),
    rawUnified: renderVariantHtml(input.diff, {
      title,
      filePath: preferredPath,
      view: "lines",
      lineMode: "raw",
      oldText: input.oldText,
      newText: input.newText,
      contextLines: DEFAULT_CONTEXT_LINES,
      lineLayout: "unified",
      showBanner: false,
      showSummary: false,
      showFilePath: false,
      layout: "embed",
      ...languageOption,
      ...semanticTokensOption,
    }),
    rawSplit: renderVariantHtml(input.diff, {
      title,
      filePath: preferredPath,
      view: "lines",
      lineMode: "raw",
      oldText: input.oldText,
      newText: input.newText,
      contextLines: DEFAULT_CONTEXT_LINES,
      lineLayout: "split",
      showBanner: false,
      showSummary: false,
      showFilePath: false,
      layout: "embed",
      ...languageOption,
      ...semanticTokensOption,
    }),
  };

  const payload = escapeScript(
    JSON.stringify({
      explain: input.explain,
      diagnostics: input.diagnostics,
      views,
    })
  );

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <style>
      :root {
        color-scheme: dark;
        --sdx-bg: #020617;
        --sdx-surface: rgba(15, 23, 42, 0.92);
        --sdx-panel: rgba(15, 23, 42, 0.74);
        --sdx-panel-strong: rgba(15, 23, 42, 0.98);
        --sdx-border: rgba(148, 163, 184, 0.24);
        --sdx-text: #e2e8f0;
        --sdx-muted: #94a3b8;
        --sdx-accent: #2dd4bf;
        --sdx-accent-strong: #14b8a6;
        --sdx-insert: #22c55e;
        --sdx-delete: #f43f5e;
        --sdx-update: #f59e0b;
        --sdx-move: #60a5fa;
        --sdx-shadow: 0 18px 40px rgba(2, 6, 23, 0.45);
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        background:
          radial-gradient(circle at top, rgba(45, 212, 191, 0.12), transparent 42%),
          linear-gradient(180deg, #020617 0%, #081120 100%);
        color: var(--sdx-text);
        font-family:
          Inter,
          ui-sans-serif,
          system-ui,
          -apple-system,
          BlinkMacSystemFont,
          "Segoe UI",
          sans-serif;
      }

      code,
      pre,
      kbd {
        font-family:
          "JetBrains Mono",
          "SFMono-Regular",
          ui-monospace,
          monospace;
      }

      .sdx-shell {
        max-width: 1600px;
        margin: 0 auto;
        padding: 24px;
      }

      .sdx-hero {
        border: 1px solid var(--sdx-border);
        border-radius: 24px;
        padding: 24px;
        background: linear-gradient(
          135deg,
          rgba(15, 23, 42, 0.98),
          rgba(15, 23, 42, 0.72)
        );
        box-shadow: var(--sdx-shadow);
      }

      .sdx-eyebrow {
        font-size: 12px;
        text-transform: uppercase;
        letter-spacing: 0.24em;
        color: var(--sdx-accent);
        font-weight: 700;
      }

      .sdx-title-row {
        display: flex;
        align-items: flex-start;
        justify-content: space-between;
        gap: 16px;
        flex-wrap: wrap;
        margin-top: 10px;
      }

      .sdx-title-row h1 {
        margin: 0;
        font-size: clamp(28px, 4vw, 40px);
      }

      .sdx-copy {
        margin: 10px 0 0;
        max-width: 70ch;
        color: var(--sdx-muted);
        line-height: 1.55;
      }

      .sdx-status {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        padding: 10px 14px;
        border-radius: 999px;
        border: 1px solid rgba(45, 212, 191, 0.25);
        background: rgba(45, 212, 191, 0.12);
        color: var(--sdx-accent);
        font-size: 13px;
        font-weight: 600;
      }

      .sdx-path-grid,
      .sdx-card-grid {
        display: grid;
        gap: 12px;
        margin-top: 18px;
      }

      .sdx-path-grid {
        grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      }

      .sdx-card-grid {
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      }

      .sdx-card {
        border: 1px solid var(--sdx-border);
        border-radius: 16px;
        background: rgba(8, 15, 31, 0.6);
        padding: 14px 16px;
      }

      .sdx-card-label {
        font-size: 11px;
        text-transform: uppercase;
        letter-spacing: 0.18em;
        color: var(--sdx-muted);
      }

      .sdx-card-value {
        margin-top: 8px;
        font-size: 20px;
        font-weight: 700;
      }

      .sdx-card-value code {
        font-size: 13px;
      }

      .sdx-pill-row,
      .sdx-summary-row {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
      }

      .sdx-summary-row {
        margin-top: 18px;
      }

      .sdx-pill {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        padding: 6px 10px;
        border-radius: 999px;
        border: 1px solid var(--sdx-border);
        background: rgba(15, 23, 42, 0.55);
        color: var(--sdx-muted);
        font-size: 12px;
      }

      .sdx-content {
        display: grid;
        grid-template-columns: minmax(0, 1.7fr) minmax(320px, 1fr);
        gap: 18px;
        margin-top: 20px;
      }

      .sdx-panel {
        border: 1px solid var(--sdx-border);
        border-radius: 20px;
        background: var(--sdx-panel);
        box-shadow: var(--sdx-shadow);
        padding: 18px;
      }

      .sdx-panel h2,
      .sdx-panel h3 {
        margin: 0;
      }

      .sdx-panel-copy {
        margin: 10px 0 0;
        color: var(--sdx-muted);
        line-height: 1.5;
      }

      .sdx-preview-toolbar {
        display: flex;
        align-items: flex-start;
        justify-content: space-between;
        gap: 16px;
        flex-wrap: wrap;
        margin-bottom: 14px;
      }

      .sdx-fieldset {
        border: 0;
        margin: 0;
        padding: 0;
        min-width: 0;
      }

      .sdx-legend {
        font-size: 11px;
        text-transform: uppercase;
        letter-spacing: 0.18em;
        color: var(--sdx-muted);
        margin-bottom: 8px;
      }

      .sdx-toggle-group {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
      }

      .sdx-toggle-group label {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        padding: 8px 12px;
        border-radius: 999px;
        border: 1px solid var(--sdx-border);
        background: rgba(8, 15, 31, 0.55);
        cursor: pointer;
        font-size: 13px;
      }

      .sdx-toggle-group input {
        accent-color: var(--sdx-accent-strong);
      }

      .sdx-toggle-group label:has(input:disabled) {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .sdx-preview-note {
        margin-top: 10px;
        color: var(--sdx-muted);
        font-size: 13px;
      }

      .sdx-preview-frame {
        width: 100%;
        height: 74vh;
        min-height: 540px;
        border: 1px solid var(--sdx-border);
        border-radius: 18px;
        background: #050815;
      }

      .sdx-sidebar {
        display: grid;
        gap: 16px;
        align-content: start;
      }

      .sdx-list {
        display: grid;
        gap: 10px;
        max-height: 300px;
        overflow: auto;
        padding-right: 4px;
        margin-top: 14px;
      }

      .sdx-item {
        border: 1px solid var(--sdx-border);
        border-radius: 16px;
        background: var(--sdx-panel-strong);
        padding: 14px;
      }

      .sdx-item-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 12px;
        flex-wrap: wrap;
      }

      .sdx-item-title {
        display: flex;
        align-items: center;
        gap: 8px;
        flex-wrap: wrap;
      }

      .sdx-item-confidence {
        color: var(--sdx-muted);
        font-size: 13px;
      }

      .sdx-type {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        min-width: 72px;
        padding: 4px 10px;
        border-radius: 999px;
        font-size: 11px;
        font-weight: 700;
        letter-spacing: 0.18em;
        text-transform: uppercase;
        border: 1px solid transparent;
      }

      .sdx-type--insert {
        color: var(--sdx-insert);
        background: rgba(34, 197, 94, 0.12);
        border-color: rgba(34, 197, 94, 0.28);
      }

      .sdx-type--delete {
        color: var(--sdx-delete);
        background: rgba(244, 63, 94, 0.12);
        border-color: rgba(244, 63, 94, 0.28);
      }

      .sdx-type--update,
      .sdx-type--rename {
        color: var(--sdx-update);
        background: rgba(245, 158, 11, 0.12);
        border-color: rgba(245, 158, 11, 0.28);
      }

      .sdx-type--move {
        color: var(--sdx-move);
        background: rgba(96, 165, 250, 0.12);
        border-color: rgba(96, 165, 250, 0.28);
      }

      .sdx-range-grid {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 10px;
        margin-top: 12px;
      }

      .sdx-range-grid code,
      .sdx-item code,
      .sdx-card code {
        word-break: break-all;
      }

      .sdx-range-label {
        display: block;
        font-size: 11px;
        text-transform: uppercase;
        letter-spacing: 0.18em;
        color: var(--sdx-muted);
        margin-bottom: 6px;
      }

      .sdx-item-copy {
        margin: 12px 0 0;
        color: var(--sdx-muted);
        line-height: 1.5;
      }

      .sdx-empty {
        border: 1px dashed var(--sdx-border);
        border-radius: 16px;
        padding: 14px;
        color: var(--sdx-muted);
        background: rgba(8, 15, 31, 0.35);
      }

      .sdx-panel-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 12px;
        flex-wrap: wrap;
      }

      .sdx-actions {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
      }

      .sdx-button {
        border: 1px solid rgba(45, 212, 191, 0.28);
        border-radius: 999px;
        background: rgba(45, 212, 191, 0.12);
        color: var(--sdx-accent);
        padding: 8px 12px;
        cursor: pointer;
        font-size: 12px;
        font-weight: 600;
      }

      details {
        margin-top: 12px;
      }

      summary {
        cursor: pointer;
        font-weight: 600;
      }

      pre {
        margin: 10px 0 0;
        padding: 12px;
        border-radius: 14px;
        border: 1px solid var(--sdx-border);
        background: rgba(2, 6, 23, 0.88);
        color: #cbd5e1;
        overflow: auto;
        max-height: 320px;
        white-space: pre-wrap;
        word-break: break-word;
        font-size: 12px;
        line-height: 1.5;
      }

      @media (max-width: 1100px) {
        .sdx-content {
          grid-template-columns: 1fr;
        }

        .sdx-preview-frame {
          height: 68vh;
        }
      }

      @media (max-width: 720px) {
        .sdx-shell {
          padding: 16px;
        }

        .sdx-hero,
        .sdx-panel {
          padding: 16px;
          border-radius: 18px;
        }

        .sdx-range-grid {
          grid-template-columns: 1fr;
        }

        .sdx-preview-frame {
          min-height: 460px;
        }
      }
    </style>
  </head>
  <body>
    <main class="sdx-shell">
      <section class="sdx-hero">
        <div class="sdx-eyebrow">Explain My Diff</div>
        <div class="sdx-title-row">
          <div>
            <h1>${escapeHtml(title)}</h1>
            <p class="sdx-copy">
              Offline workbench with embedded rendered views, explain output, and diagnostics.
            </p>
          </div>
          <div class="sdx-status">No server required</div>
        </div>

        <div class="sdx-path-grid">
          <div class="sdx-card">
            <div class="sdx-card-label">Old path</div>
            <div class="sdx-card-value"><code>${escapeHtml(shownOldPath)}</code></div>
          </div>
          <div class="sdx-card">
            <div class="sdx-card-label">New path</div>
            <div class="sdx-card-value"><code>${escapeHtml(shownNewPath)}</code></div>
          </div>
          <div class="sdx-card">
            <div class="sdx-card-label">Detected language</div>
            <div class="sdx-card-value">${escapeHtml(input.language ?? "text")}</div>
          </div>
        </div>

        <div class="sdx-card-grid">
          <div class="sdx-card">
            <div class="sdx-card-label">Operations</div>
            <div class="sdx-card-value">${input.diagnostics.summary.operationCount}</div>
          </div>
          <div class="sdx-card">
            <div class="sdx-card-label">Moves</div>
            <div class="sdx-card-value">${input.diagnostics.summary.moveCount}</div>
          </div>
          <div class="sdx-card">
            <div class="sdx-card-label">Renames</div>
            <div class="sdx-card-value">${input.diagnostics.summary.renameCount}</div>
          </div>
          <div class="sdx-card">
            <div class="sdx-card-label">Diagnostics bundle</div>
            <div class="sdx-card-value">${escapeHtml(
              input.diagnostics.redacted ? "Redacted" : "Includes code"
            )}</div>
          </div>
        </div>

        <div class="sdx-summary-row">
          <span class="sdx-pill">${operationCounts.insert} inserts</span>
          <span class="sdx-pill">${operationCounts.delete} deletes</span>
          <span class="sdx-pill">${operationCounts.update} updates</span>
          <span class="sdx-pill">${operationCounts.move} move ops</span>
        </div>
      </section>

      <div class="sdx-content">
        <section class="sdx-panel">
          <div class="sdx-preview-toolbar">
            <div>
              <fieldset class="sdx-fieldset">
                <div class="sdx-legend">Mode</div>
                <div class="sdx-toggle-group">
                  <label>
                    <input type="radio" name="sdx-view" value="semantic-structure" checked />
                    <span>Semantic structure</span>
                  </label>
                  <label>
                    <input type="radio" name="sdx-view" value="semantic-lines" />
                    <span>Semantic lines</span>
                  </label>
                  <label>
                    <input type="radio" name="sdx-view" value="raw-lines" />
                    <span>Raw lines</span>
                  </label>
                </div>
              </fieldset>
              <div id="sdx-preview-note" class="sdx-preview-note"></div>
            </div>

            <fieldset class="sdx-fieldset">
              <div class="sdx-legend">Layout</div>
              <div class="sdx-toggle-group">
                <label>
                  <input type="radio" name="sdx-layout" value="unified" checked />
                  <span>Unified</span>
                </label>
                <label>
                  <input type="radio" name="sdx-layout" value="split" />
                  <span>Split</span>
                </label>
              </div>
            </fieldset>
          </div>

          <iframe
            id="sdx-preview-frame"
            class="sdx-preview-frame"
            title="SemaDiff inspect preview"
          ></iframe>
        </section>

        <aside class="sdx-sidebar">
          <section class="sdx-panel">
            <h2>Explanation panel</h2>
            <p class="sdx-panel-copy">
              Review semantic operations, grouped moves and renames, then compare the rendered diff modes in the preview.
            </p>
          </section>

          <section class="sdx-panel">
            <div class="sdx-panel-header">
              <h3>Operations</h3>
              <span class="sdx-pill">${input.explain.operations.length} explained</span>
            </div>
            <div class="sdx-list">${buildOperationItems(input.diff, input.explain)}</div>
          </section>

          <section class="sdx-panel">
            <div class="sdx-panel-header">
              <h3>Moves</h3>
              <span class="sdx-pill">${input.explain.moves.length} groups</span>
            </div>
            <div class="sdx-list">${buildMoveItems(input.diff, input.explain)}</div>
          </section>

          <section class="sdx-panel">
            <div class="sdx-panel-header">
              <h3>Renames</h3>
              <span class="sdx-pill">${input.explain.renames.length} groups</span>
            </div>
            <div class="sdx-list">${buildRenameItems(input.diff, input.explain)}</div>
          </section>

          <section class="sdx-panel">
            <h3>Diagnostics summary</h3>
            <div class="sdx-summary-row">
              <span class="sdx-pill">${input.diagnostics.summary.operationCount} operations</span>
              <span class="sdx-pill">${input.diagnostics.summary.moveCount} moves</span>
              <span class="sdx-pill">${input.diagnostics.summary.renameCount} renames</span>
              <span class="sdx-pill">${escapeHtml(
                input.diagnostics.redacted
                  ? "Bundle redacted"
                  : "Bundle includes code"
              )}</span>
            </div>
          </section>

          <section class="sdx-panel">
            <div class="sdx-panel-header">
              <h3>Embedded JSON</h3>
              <div class="sdx-actions">
                <button type="button" class="sdx-button" data-download="explain">
                  Download explain.json
                </button>
                <button type="button" class="sdx-button" data-download="diagnostics">
                  Download diagnostics.json
                </button>
              </div>
            </div>

            <details open>
              <summary>Explain JSON</summary>
              <pre id="sdx-explain-json"></pre>
            </details>

            <details>
              <summary>Diagnostics JSON</summary>
              <pre id="sdx-diagnostics-json"></pre>
            </details>
          </section>
        </aside>
      </div>
    </main>

    <script>
      globalThis.__SEMADIFF_INSPECT__ = ${payload};
    </script>
    <script>
      (() => {
        const data = globalThis.__SEMADIFF_INSPECT__;
        const preview = document.getElementById("sdx-preview-frame");
        const previewNote = document.getElementById("sdx-preview-note");
        const explainJson = document.getElementById("sdx-explain-json");
        const diagnosticsJson = document.getElementById("sdx-diagnostics-json");
        const viewInputs = Array.from(
          document.querySelectorAll('input[name="sdx-view"]')
        );
        const layoutInputs = Array.from(
          document.querySelectorAll('input[name="sdx-layout"]')
        );

        if (explainJson) {
          explainJson.textContent = JSON.stringify(data.explain, null, 2);
        }
        if (diagnosticsJson) {
          diagnosticsJson.textContent = JSON.stringify(data.diagnostics, null, 2);
        }

        const downloads = {
          explain: {
            filename: "semadiff-explain.json",
            value: data.explain,
          },
          diagnostics: {
            filename: "semadiff-diagnostics.json",
            value: data.diagnostics,
          },
        };

        const buttonElements = Array.from(
          document.querySelectorAll("[data-download]")
        );
        for (const button of buttonElements) {
          button.addEventListener("click", () => {
            const key = button.getAttribute("data-download");
            if (!key || !(key in downloads)) {
              return;
            }
            const { filename, value } = downloads[key];
            const blob = new Blob([JSON.stringify(value, null, 2)], {
              type: "application/json",
            });
            const href = URL.createObjectURL(blob);
            const link = document.createElement("a");
            link.href = href;
            link.download = filename;
            link.click();
            setTimeout(() => URL.revokeObjectURL(href), 1_000);
          });
        }

        function selectedValue(name, fallback) {
          const selected = document.querySelector('input[name="' + name + '"]:checked');
          return selected instanceof HTMLInputElement ? selected.value : fallback;
        }

        function currentViewKey(view, layout) {
          if (view === "semantic-lines") {
            return layout === "split" ? "semanticSplit" : "semanticUnified";
          }
          if (view === "raw-lines") {
            return layout === "split" ? "rawSplit" : "rawUnified";
          }
          return "semanticStructure";
        }

        function renderPreview() {
          const view = selectedValue("sdx-view", "semantic-structure");
          const layout = selectedValue("sdx-layout", "unified");
          const layoutEnabled = view !== "semantic-structure";
          for (const input of layoutInputs) {
            input.disabled = !layoutEnabled;
          }

          if (previewNote) {
            previewNote.textContent = layoutEnabled
              ? "Switch between unified and split layouts for the selected line view."
              : "Semantic structure view reuses the semantic operation renderer and ignores line layout.";
          }

          if (preview instanceof HTMLIFrameElement) {
            preview.srcdoc = data.views[currentViewKey(view, layout)] ?? data.views.semanticStructure;
          }
        }

        for (const input of [...viewInputs, ...layoutInputs]) {
          input.addEventListener("change", renderPreview);
        }

        renderPreview();
      })();
    </script>
  </body>
</html>`;
}

export function resolveInspectOutputPath(outputPath?: string) {
  if (outputPath && outputPath.trim().length > 0) {
    return path.resolve(outputPath);
  }
  const directory = mkdtempSync(path.join(tmpdir(), "semadiff-inspect-"));
  return path.join(directory, "index.html");
}

export function writeInspectWorkbench(outputPath: string, html: string) {
  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, html, "utf8");
}

export function openInspectWorkbench(outputPath: string) {
  const target = pathToFileURL(outputPath).href;
  let candidates:
    | readonly { command: string; args: readonly string[] }[]
    | undefined;
  if (process.platform === "darwin") {
    candidates = [{ command: "open", args: [target] }];
  } else if (process.platform === "win32") {
    candidates = [{ command: "cmd", args: ["/c", "start", "", target] }];
  } else {
    candidates = [
      { command: "xdg-open", args: [target] },
      { command: "gio", args: ["open", target] },
    ];
  }

  let lastError: unknown;
  for (const candidate of candidates) {
    const result = spawnSync(candidate.command, candidate.args, {
      stdio: "ignore",
    });
    if (!result.error && result.status === 0) {
      return;
    }
    lastError =
      result.error ??
      new Error(
        `Failed to open inspect workbench with ${candidate.command} (exit ${result.status ?? "unknown"}).`
      );
  }

  throw lastError ?? new Error("Failed to open inspect workbench.");
}
